### ISSUE TITLE
Error: listen EADDRINUSE :::8000 after change to Main.elm

### ISSUE THREAD

**Issue by wolfadex** [wking-io/elm-live#147] opened 2018-11-06 16:34 UTC
When I run `elm-live src/Main.elm -e node_modules/.bin/elm -o -- --debug` everything works as normal/expected. Then when I make a change to Main.elm
```elm
view : Model -> Html Msg
view model =
  div []
    [ button [ onClick Decrement ] [ text "-" ]
    , div [] [ text (String.fromInt model) ]
    , button [ onClick Increment ] [ text "+" ]
    ]
```
such as commenting out `view : Model -> Html Msg`, the console starts repeatedly spamming:
```
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8000
    at Server.setupListenHandle [as _listen2] (net.js:1286:14)
    at listenInCluster (net.js:1334:12)
    at Server.listen (net.js:1421:7)
    at Object.<anonymous> (/Users/wolfgang.schuster/Experiment/elm/ark/node_modules/elm-serve/lib/elm-reload-server.js:93:8)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
Emitted 'error' event at:
    at Server.emit (events.js:182:13)
    at emitErrorNT (net.js:1313:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
```
OS: OSX 10.13.6
Node: 10.12.0

When using Node 8.12.0 the error changes to:
```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8000
    at Server.setupListenHandle [as _listen2] (net.js:1360:14)
    at listenInCluster (net.js:1401:12)
    at Server.listen (net.js:1485:7)
    at Object.<anonymous> (/Users/wolfgang.schuster/Experiment/elm/ark/node_modules/elm-serve/lib/elm-reload-server.js:93:8)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
```

**Comment by wking-io** [comment] 2018-11-06 19:44
What version of `elm-live` are you using?

**Comment by wolfadex** [comment] 2018-11-06 19:46
"devDependencies": {
    "elm": "^0.19.0-bugfix2",
    "elm-live": "^3.2.1"
  }

**Comment by wking-io** [comment] 2018-11-06 19:59
So that error you are experiencing is caused generally when you have multiple processes running on the same port. Did you check to see if you had anything else running on port 8000?

This article helped me figure out if that was the problem when I did this once: https://medium.freecodecamp.org/find-and-kill-port-processes-on-a-mac-using-bash-c5e95b9e704e

**Comment by wolfadex** [comment] 2018-11-06 20:20
Before starting `elm-live` running `lsof -t -i :8000` displays nothing. After starting `elm-live `lsof -t -i :8000` displays 2 PIDs

**Comment by wking-io** [comment] 2018-11-07 14:07
Okay thanks for the update let me look into that! Do you have this project in a repo I can take a look at? Not able to reproduce locally for me.

**Comment by wolfadex** [comment] 2018-11-07 16:14
https://github.com/wolfadex/ark thanks again for all the help! I'll attempt to reproduce it on some other computers too, see if I can help narrow it down

**Comment by wolfadex** [comment] 2018-11-07 17:06
I've also tested my repo on Ubuntu 18.04 and am getting the same error, FYI

**Comment by wking-io** [comment] 2018-11-08 18:34
Thanks for the repo on other info! I will take a look into this and see what I can dig up!

**Comment by wking-io** [comment] 2018-11-08 18:46
Hey! So I cloned the repo and everything is working on my end. Could you do me a favor. Could you try installing past versions of elm-live and see if any of them start working for you?

**Comment by wking-io** [comment] 2018-11-08 18:46
That way we can maybe pinpoint where a change might have caused it.

**Comment by wolfadex** [comment] 2018-11-09 01:13
So I think it's Yarn. If I do `npm run dev` or `npx elm-live src/Main.elm -e node_modules/.bin/elm -- --debug` then everything works as expected, but running it with `yarn dev` causes the errors. I'm going to see if I can do a little more digging to better pin point the issue.

Yarn v1.12.1 btw, and thank you for all the help!

**Comment by wking-io** [comment] 2018-11-09 02:48
Ahh that is interesting. I am glad you were able to figure out what the problem was. Now I am curious what the cause is  🤔

**Comment by wolfadex** [comment] 2018-11-09 02:53
I'll try to install some earlier versions of yarn, see if there's a version that does work.

**Comment by axelo** [comment] 2018-11-12 15:36
I am experiencing the same issue with yarn 1.12.1 and 1.12.3, but works fine with yarn 1.10.1 and of course npm (5.6.0).

**Comment by Natim** [comment] 2018-11-26 15:23
I am glad to see it is related to yarn rather than elm live. I will use `npm run live` instead of `yarn live` for now.

**Comment by jpierson** [comment] 2019-05-16 10:25
I'm running into this issue using npm scripts, not yarn.

ex.
```json
{
  "scripts": {
    "debug": "elm-live src/Main.elm --open --path-to-elm ./node_modules/elm/bin/elm  -- --output=elm.js --debug"
  },
}
```

OS: Windows 10
Node: v10.9.0
NPM: 6.1.0

```
{
  "devDependencies": {
    "elm": "^0.19.0-no-deps",
    "elm-format": "^0.8.1",
    "elm-live": "^3.4.0",
    "elm-test": "^0.19.0-rev6"
  }
}
```

**Comment by jpierson** [comment] 2019-05-16 10:42
Unlike others I see the same problem when running elm-live directly with npx or with node from the console.

With npx:
```
npx elm-live src/Main.elm --open --path-to-elm ./node_modules/elm/bin/elm  -- --output=main.js --debug
```

Directly with node:
```
node node_modules/elm-live/bin/elm-live.js src/Main.elm --open --path-to-elm ./node_modules/elm/bin/elm  -- --output=main.js --debug
```

**Comment by jpierson** [comment] 2019-06-05 16:41
After updating from `v3.4.0` to `v3.4.1` I'm seeing different behavior. Now it doesn't look like any change made in a .elm file is triggering elm-make or any activity at all. This is specific to my setup on Windows 10, I haven't tried any other environments yet.

**Comment by wking-io** [comment] 2019-07-24 03:40
This should be fixed in the new alpha! You can check the README for how to install it.

**Closed by wking-io** 2019-07-24 03:40 UTC
