### ISSUE TITLE
ERR_INVALID_ARG_TYPE Error in alpha 

### ISSUE THREAD

**Issue by girishso** [wking-io/elm-live#177] opened 2019-07-25 15:40 UTC
Just trying out alpha version, I get following error. Any ideas?

```
> elm-live ./src/Main.elm  --open  -- --output=./src/static/elm.js

_http_server.js:302
    throw new ERR_INVALID_ARG_TYPE('options', 'object', options);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "options" argument must be of type object. Received type boolean
    at new Server (_http_server.js:302:11)
    at Object.createServer (http.js:40:10)
at /Users/XX/.config/yarn/global/node_modules/elm-live/lib/src/start.js:244:75
at /Users/XX/.config/yarn/global/node_modules/crocks/core/compose.js:8:14
at settle (/Users/XX/.config/yarn/global/node_modules/crocks/Async/index.js:151:16)
at /Users/XX/.config/yarn/global/node_modules/crocks/Async/index.js:27:62
at fork (/Users/XX/.config/yarn/global/node_modules/crocks/Async/index.js:155:20)
at /Users/XX/.config/yarn/global/node_modules/crocks/Async/index.js:224:16
at fork (/Users/XX/.config/yarn/global/node_modules/crocks/Async/index.js:155:20)
at /Users/XX/.config/yarn/global/node_modules/crocks/Async/index.js:224:16
```

**Comment by wking-io** [comment] 2019-07-25 16:24
What Node version are you using?

**Comment by wking-io** [comment] 2019-07-25 16:34
Try installing the new alpha and let me know if the issue is fixed!

**Comment by girishso** [comment] 2019-07-26 01:11
Tried the new alpha, now the server starts but when accessing it in browser it crashes.

I'm on Mac btw.

```
╰→  elm-live --version
4.0.0-alpha.3

╰→  node -v
v12.6.0

╰→  elm-live ./src/Main.elm  --open  -- --output=./src/static/elm.js
.
.

internal/fs/utils.js:426
    throw new ERR_INVALID_ARG_TYPE(propName, ['string', 'Buffer', 'URL'], path);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type undefined
    at readFile (fs.js:302:10)
    at /Users/girish/.config/yarn/global/node_modules/crocks/Async/index.js:54:10
    at Object.fork (/Users/girish/.config/yarn/global/node_modules/crocks/Async/index.js:155:20)
    at /Users/girish/.config/yarn/global/node_modules/crocks/Async/index.js:254:41
    at settle (/Users/girish/.config/yarn/global/node_modules/crocks/Async/index.js:151:16)
    at ReadFileContext.callback (/Users/girish/.config/yarn/global/node_modules/crocks/Async/index.js:56:47)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:246:13)
```

**Comment by wking-io** [comment] 2019-07-26 01:13
Do you have you project in a repo I can use to test?

**Comment by wking-io** [comment] 2019-08-07 00:30
This should be fixed now! 👌

**Closed by wking-io** 2019-08-07 00:30 UTC
