### ISSUE TITLE
Can not access html

### ISSUE THREAD

**Issue by justgook** [wking-io/elm-live#139] opened 2018-09-17 14:49 UTC
I have structure:
 * index.html
 * data
   * test.html

and if i start `elm-live` and navigate `http://localhost:8000/data/test.html` i got content of compiled elm, not html that i expect

**Comment by Odalrick** [comment] 2018-09-25 09:22
I had the same problem. 

I think I traced it to https://github.com/wking-io/elm-serve/blob/edbfbb08fbeb5d7badc3e29dcaf22fe3197cbf38/lib/elm-reload-server.js#L38

Essentially regardless, if the path requested ends with "html", the index gets served.

I worked around it by changing my test file extension to "htm".

**Comment by wking-io** [comment] 2018-09-27 03:49
Hey! So are you saying that even without pushstate being turned on you are always having your index.html loaded?

**Comment by Odalrick** [comment] 2018-09-27 07:56
An autogenerated index-file, yes, as long as the file requested has the "html" extension. At least that's the way it appears.

**Comment by wking-io** [comment] 2018-09-27 11:30
@Odalrick @justgook Do either of you have a repo where the issue happens I can take a look at and test around?

**Comment by justgook** [comment] 2018-09-27 11:59
is example not enough ?

**Comment by wking-io** [comment] 2018-09-27 12:05
Oh sure, but if you had an exact representation of your project then I wouldn't have to set anything up and would be able to know without a doubt when I solve your issue! 😊 If you don't that is fine I can set something up. Just want to make sure I get this figured out for you both.  👌

**Comment by Odalrick** [comment] 2018-09-27 12:06
I created a minimal example in https://github.com/Odalrick/automatic-spork

To recreate the problem as I have it run 
`yarn run test-test-dev`
and go to http://localhost:8000/src/html/test-test.html

http://localhost:8000/src/html/test-test.htm works, but notice that the reload script is manually added.

**Comment by wking-io** [comment] 2018-09-27 12:29
@Odalrick I removed the reload script from `test-test.html` and ran the command and it worked exactly as expected. Live reload and the page loaded as expected. Am I missing something?

**Comment by Odalrick** [comment] 2018-09-27 13:00
That's very strange.

What _I_ get is:

![screen shot 2018-09-27 at 14 58 42](https://user-images.githubusercontent.com/222897/46147527-fbfdcd80-c265-11e8-9fc3-78b6b58baa22.png)

compared to what I expect:

![screen shot 2018-09-27 at 14 58 29](https://user-images.githubusercontent.com/222897/46147550-0750f900-c266-11e8-82b5-3a36cf5a0442.png)

**Comment by Odalrick** [comment] 2018-09-27 13:15
To be clear, the script runs for on the "html" page, it's just that the static content around the element isn't there, presumably because it sends the index page.

**Comment by wking-io** [comment] 2018-09-27 13:34
This is what I see when I run it:

<img width="903" alt="screenshot 2018-09-27 08 32 12" src="https://user-images.githubusercontent.com/11789828/46149492-11f09b80-c230-11e8-923e-8a7b976ae87c.png">

**Comment by Odalrick** [comment] 2018-09-27 13:55
This is amazing, I added some console.log to https://github.com/wking-io/elm-serve/blob/edbfbb08fbeb5d7badc3e29dcaf22fe3197cbf38/lib/elm-reload-server.js#L42 .

    const finalpath =
      (pushstate || pathname === '/' || pathname === '')
        ? (dir + '/' + startPage)
        : (dir + '/' + pathname);
    const test =
      false
        ? (dir + '/' + startPage)
        : (dir + '/' + pathname);
    console.log('pushstate', pushstate)
    console.log('pathname === \'/\'', pathname === '/')
    console.log("pathname === ''", pathname === '')
    console.log("(pushstate || pathname === '/' || pathname === '')", (pushstate || pathname === '/' || pathname === ''))
    console.log('finalpath', finalpath)
    console.log('test     ', test)
    console.log("(dir + '/' + startPage)", (dir + '/' + startPage))
    console.log("(dir + '/' + pathname)", (dir + '/' + pathname))
    console.log('startPage', startPage)
    console.log('pathname', pathname)


The output is:

    pushstate false
    pathname === '/' false
    pathname === '' false
    (pushstate || pathname === '/' || pathname === '') false
    finalpath /Users/ulrik/projects/test-test/index.html
    test      /Users/ulrik/projects/test-test/src/html/test-test.html
    (dir + '/' + startPage) /Users/ulrik/projects/test-test/index.html
    (dir + '/' + pathname) /Users/ulrik/projects/test-test/src/html/test-test.html
    startPage index.html
    pathname src/html/test-test.html

**Comment by Odalrick** [comment] 2018-09-27 14:38
I found it!

    console.log('pushstate', pushstate)
    console.log('typeof pushstate', typeof pushstate)

    pushstate false
    typeof pushstate string

pushstate is the _string_ "false", which is of course truthy.

Maybe our versions of minimist has changed some detail in defaults? You can of course see the exact version I have in the yarn.lock file.

Seems appropriate that the problem is something that just couldn't happen in Elm.

**Comment by wking-io** [comment] 2018-09-27 14:41
Hahah I know right! :Thanks for finding the problem! I will get a fix figured out and shipped over on `elm-serve`

**Comment by wking-io** [comment] 2018-09-27 14:56
Okay just pushed update! Try elm-live 3.0.6 and let me know!

**Comment by wking-io** [comment] 2018-09-30 03:43
Closing issue @justgook. Let me know if this issue wasn't resolved for your case with the new release.

**Comment by justgook** [comment] 2018-10-01 07:18
clone - https://github.com/justgook/justgook.github.io/tree/develop
Start:
`elm-live src/Main.elm --open --pushstate --dir=./gh-pages -- --debug --output=./gh-pages/bundle.js`

open: http://localhost:8000/wizardry/level - you will see - that all pages that is level.html, is redirected to index.

**Comment by wking-io** [comment] 2018-10-01 11:44
Looks like you are using the `--pushstate` option. That option is what turns on the feature where all paths in the URL are redirected to the index.html on purpose so that `Browser.application` handles routing clientside. Just remove that option and it will turn that off

**Comment by justgook** [comment] 2018-10-01 13:28
dosent it should redirect to index.html only files that not exist in tree?

**Comment by wking-io** [comment] 2018-10-03 12:39
I do not know if I am following?

**Comment by justgook** [comment] 2018-10-03 12:47
idea is that im have some webpage, that should redirect to index page, if it try access page that not exist, that is basic pattern of SPA.. all pages that is 404 - should get instead index.html:200  

but now im getting index.html, each time, when i try request any html page (IMPO that is wrong)

**Comment by wking-io** [comment] 2018-10-03 13:27
So what you would expect when using `--pushstate` is that any url without an extension (html, css, js) should auto serve the index.html, but if you use a url with an extension it should deliver that page?

**Comment by justgook** [comment] 2018-10-04 07:40
NO - my expectation is that any file that exist must be served, and if it not exist it must serve index.html (IMPO that is how any SPA works)

**Comment by wking-io** [comment] 2018-11-06 14:52
@justgook Just released a new version that fixes this problem! Now the behavior is the following:

- If the url doesn't have an html extension it defaults to the index and lets elm handle routing
- If the url has an .html extension it will try and serve the file, but if it returns a 404 then it will serve the index and let elm handle routing

**Closed** 2018-11-19 18:32 UTC
