### ISSUE TITLE
The reloading script is not injected if the html file has a dot in its name

### ISSUE THREAD

**Issue by lucarakuten** [wking-io/elm-live#163] opened 2019-02-25 06:00 UTC
I have a file named "index.start.html" and elm-live is not injecting the snippet for reloading the page:

     
    <script src="/reload/reload.js"></script>
    

Just removing the dot in the file name (for example "index-start.html") solve the issue.

**Comment by harrysarson** [comment] 2019-02-25 12:28
This error is caused by: https://github.com/wking-io/elm-serve/blob/29cef9689cb2e23e7a82a6254446aebe62937a51/lib/elm-reload-server.js#L47 an https://github.com/wking-io/elm-serve/blob/29cef9689cb2e23e7a82a6254446aebe62937a51/lib/elm-reload-server.js#L51.

(Note that these files are not actually in this repository)

Seems to me that using the built in `path` module would be the best way to solve this.

**Comment by magopian** [comment] 2019-02-26 10:01
I'm not sure if it's the same issue, or even related, but you can't have a dot in the URLs at all, eg `/register/foo@bar.com` will result in the following error message:

```
Cannot GET /register/foo@bar.com
```

**Comment by wking-io** [comment] 2019-06-07 03:49
These are all related! I will have a fix for this in the next release coming soon! :)

**Comment by wking-io** [comment] 2019-07-24 03:10
This should be fixed in the new alpha! You can check the README for how to install it.

**Closed by wking-io** 2019-07-24 03:10 UTC
